server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: starzplay-assignment
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
    level:
        ROOT: INFO
        ae.starzplay.assignment.config: DEBUG
        org.springframework: ERROR
        io.swagger.models.parameters.AbstractSerializableParameter: ERROR
